modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
    modId="alubapvpmod"
    version="1.0"
    displayName="Aluba PVP Mod"
    description='By in Aluba'
    authors="Aluba"

[[dependencies.alubapvpmod]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.alubapvpmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
